INSERT INTO m3c.mana_box_collection (
    "id",
    "name",
    "creation_date",
    "binder_names"
) VALUES (
    'a7397c6a-a29f-4495-898c-028355708f33',
    'Collection Julian',
    '2026-02-14T14:44:00+01:00',
    'Decks||Hors-decks||Tmp'
);
INSERT INTO m3c.mana_box_collection (
    "id",
    "name",
    "creation_date",
    "binder_names"
) VALUES (
    'b3872bf9-b043-48f3-b16e-f21050fb65cd',
    'Collection Julian 2',
    '2026-02-16T14:44:00+01:00',
    'Decks||Hors-decks||Tmp'
);

INSERT INTO m3c.mana_box_card (
    "id",
    "scryfall_id",
    "binder_name",
    "binder_type",
    "name",
    "set_code",
    "set_name",
    "collector_number",
    "foil",
    "rarity",
    "quantity",
    "purchase_price",
    "misprint",
    "altered",
    "condition",
    "language",
    "purchase_price_currency",
    "id_collection"
) VALUES (
    54680,
    'a48c3a2f-678b-4e70-a53f-258457d88d29',
    'Hors-decks',
    'binder',
    'Field Research',
    'ZNR',
    'Zendikar Rising',
    58,
    'normal',
    'common',
    4,
    0.07,
    false,
    false,
    'near_mint',
    'fr',
    'EUR',
    'a7397c6a-a29f-4495-898c-028355708f33'
);

INSERT INTO m3c.mana_box_card (
    "id",
    "scryfall_id",
    "binder_name",
    "binder_type",
    "name",
    "set_code",
    "set_name",
    "collector_number",
    "foil",
    "rarity",
    "quantity",
    "purchase_price",
    "misprint",
    "altered",
    "condition",
    "language",
    "purchase_price_currency",
    "id_collection"
) VALUES (
    54832,
    'faf65512-8228-48f4-ba7b-d861b66d28c9',
    'Hors-decks',
    'binder',
    'Oblivion''s Hunger',
    'ZNR',
    'Zendikar Rising',
    119,
    'normal',
    'common',
    4,
    0.06,
    false,
    false,
    'near_mint',
    'fr',
    'EUR',
    'a7397c6a-a29f-4495-898c-028355708f33'
);

INSERT INTO m3c.mana_box_card (
    "id",
    "scryfall_id",
    "binder_name",
    "binder_type",
    "name",
    "set_code",
    "set_name",
    "collector_number",
    "foil",
    "rarity",
    "quantity",
    "purchase_price",
    "misprint",
    "altered",
    "condition",
    "language",
    "purchase_price_currency",
    "id_collection"
) VALUES (
    54433,
    '0b057eb7-8439-4d26-89df-c345ab2773e1',
    'Hors-decks',
    'binder',
    'Roiling Vortex',
    'ZNR',
    'Zendikar Rising',
    156,
    'normal',
    'rare',
    4,
    1.49,
    false,
    false,
    'near_mint',
    'fr',
    'EUR',
    'a7397c6a-a29f-4495-898c-028355708f33'
);

INSERT INTO m3c.mana_box_card (
    "id",
    "scryfall_id",
    "binder_name",
    "binder_type",
    "name",
    "set_code",
    "set_name",
    "collector_number",
    "foil",
    "rarity",
    "quantity",
    "purchase_price",
    "misprint",
    "altered",
    "condition",
    "language",
    "purchase_price_currency",
    "id_collection"
) VALUES (
    54691,
    'ad57c2f3-d9cb-4165-bb39-897b5b12689e',
    'Hors-decks',
    'binder',
    'Teeterpeak Ambusher',
    'ZNR',
    'Zendikar Rising',
    169,
    'normal',
    'common',
    8,
    0.05,
    false,
    false,
    'near_mint',
    'fr',
    'EUR',
    'b3872bf9-b043-48f3-b16e-f21050fb65cd'
);

INSERT INTO m3c.mana_box_card (
    "id",
    "scryfall_id",
    "binder_name",
    "binder_type",
    "name",
    "set_code",
    "set_name",
    "collector_number",
    "foil",
    "rarity",
    "quantity",
    "purchase_price",
    "misprint",
    "altered",
    "condition",
    "language",
    "purchase_price_currency",
    "id_collection"
) VALUES (
    54687,
    'ab62382d-2dc9-4a60-b031-c845ebad0357',
    'Hors-decks',
    'binder',
    'Cragplate Baloth',
    'ZNR',
    'Zendikar Rising',
    183,
    'normal',
    'rare',
    2,
    0.18,
    false,
    false,
    'near_mint',
    'fr',
    'EUR',
    'b3872bf9-b043-48f3-b16e-f21050fb65cd'
);